trigger:
  - feature/*
  - master  

parameters:
  - name: variable_group
    default: "dev"
    values:
      - "i-platform-dev"
      - "astra"
      - "ossaas"
      - "sandbox"

pr: none

stages:
  - stage: buildPublishImage
    displayName: Build and publish Docker Image to ECR
    jobs:
      - job: BuildAgent
        displayName: Building Azure Agent Image
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          - group: ${{ parameters.variable_group }}
          - name: DOCKER_REPOSITORY
            value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)

        steps:
          - script: |
              eval $(aws ecr get-login --no-include-email --region $(AWS_REGION))
            displayName: AWS ECR Login
            
          - script: |
              echo $sourceVersion
              commitHash=${sourceVersion:0:7}
              echo $commitHash
              echo "##vso[task.setvariable variable=commitHash]$commitHash"
            env: { sourceVersion: $(Build.SourceVersion) }
            displayName: Refactor Git Hash to 7-digits
            
          - task: Docker@2
            displayName: Build and Publish Terraform And Terragrunt Image 
            inputs:
              repository: $(DOCKER_REPOSITORY)
              command: buildAndPush
              Dockerfile: Dockerfile
              tags: |
                $(commitHash)
